#!/usr/bin/env python3
"""Regenerate WEAKNESS.md from the structured record.

    python3 coach/tally.py             # rewrite WEAKNESS.md
    python3 coach/tally.py --archive   # also retire this campaign's history

WEAKNESS.md is coach-owned and fully derived, so this overwrites it. The
source of truth is progress.json -> history (per-problem bucket, outcome and
time on clock) plus coach/history-archive.json for closed campaigns. LOG.md
stays the human narrative and is never parsed for numbers.
"""
import argparse
import json
import sys

from _state import State, BUCKET_DESC, p

ARCHIVE = 'coach/history-archive.json'


def load_archive():
    try:
        with open(p('coach', 'history-archive.json'), encoding='utf-8') as f:
            return json.load(f)
    except Exception:
        return []


def counts(rows):
    c = {1: 0, 2: 0, 3: 0, 4: 0}
    for r in rows:
        b = r.get('bucket')
        if b in c:
            c[b] += 1
    return c


def table(c):
    n = sum(c.values())
    out = ['| Bucket | Count | Share |', '|---|---|---|']
    for b in (1, 2, 3, 4):
        pct = f'{round(c[b] / n * 100)}%' if n else '—'
        out.append(f'| {b} — {BUCKET_DESC[b]} | {c[b]} | {pct} |')
    return '\n'.join(out), n


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--archive', action='store_true')
    a = ap.parse_args()

    s = State()
    current = s.history
    archived = load_archive()
    alltime = archived + current

    ct_all, n_all = table(counts(alltime))
    ct_cur, n_cur = table(counts(current))

    # topic hit rate
    agg = {}
    for r in alltime:
        t = s.topic(r['qid'])
        c, n = agg.get(t, (0, 0))
        agg[t] = (c + (1 if r.get('bucket') == 4 else 0), n + 1)
    if agg:
        rows = ['| Topic | Clean | Attempts | Rate |', '|---|---|---|---|']
        for t, (c, n) in sorted(agg.items(), key=lambda kv: kv[1][0] / kv[1][1]):
            rows.append(f'| {t} | {c} | {n} | {round(c / n * 100)}% |')
        topic_md = '\n'.join(rows)
    else:
        topic_md = '_(no logged attempts yet)_'

    # re-solve queue
    q = s.resolve_queue
    if q:
        qmd = '\n'.join(f'- `{qid}` — {s.name(qid)} ({s.topic(qid)})' for qid in q)
    else:
        qmd = '_(empty)_'

    # leetcode conflicts
    lc = s.leetcode or {}
    rec = lc.get('reconcile') or {}
    conf = rec.get('conflicts') or []
    if conf:
        cmd = '\n'.join(
            f'- {s.name(c["qid"])} — sheet says `{c["sheet"]}`, LeetCode has it accepted'
            for c in conf)
    else:
        cmd = '_(none, or LeetCode not synced)_'

    unver = rec.get('unverified') or []
    umd = ('\n'.join(f'- {s.name(u["qid"])}' for u in unver[:20])
           if unver else '_(none)_')

    clean_rate = f'{round(counts(alltime)[4] / n_all * 100)}%' if n_all else '—'

    doc = f"""# WEAKNESS

The standing skill model. **This file never resets** — campaigns archive, this
accumulates. Generated by `python3 coach/tally.py`; don't edit by hand.

Buckets: 1 = pattern not recognised · 2 = pattern known, implementation failed ·
3 = solved but slow / brute-force / messy · 4 = clean solve in cap.

## Bucket tally — all time

{ct_all}

Clean rate **{clean_rate}** over {n_all} logged attempts.

## Bucket tally — current campaign

{ct_cur}

{n_cur} attempts logged this campaign.

## Topic hit rate

Clean solves inside the cap, over attempts. Only counts problems actually
attempted on a timer — sheet status and LeetCode accepts don't feed this.

{topic_md}

## Re-solve queue

Every capped problem enters. It leaves only on a clean solve from blank on a
later day — not on a LeetCode accept, which is untimed and usually assisted.

{qmd}

## Conflicts

LeetCode reports these as accepted while the sheet has them failed or
needs-revision. Solved eventually, but not under the cap.

{cmd}

## Claimed but unverified

Marked mastered in the sheet with no accepted LeetCode submission behind them.
Either solved elsewhere, or marked optimistically.

{umd}
"""

    with open(p('WEAKNESS.md'), 'w', encoding='utf-8') as f:
        f.write(doc)
    print(f'WEAKNESS.md rewritten — {n_all} all-time attempts, {n_cur} this campaign')

    if a.archive:
        with open(p('coach', 'history-archive.json'), 'w', encoding='utf-8') as f:
            json.dump(alltime, f, indent=1)
        print(f'archived {len(current)} attempts into {ARCHIVE}')
        print('now clear state.coach.history in the sheet, or it double-counts')
    return 0


if __name__ == '__main__':
    sys.exit(main())
